package com.histocons.entidades;
// Generated 20-jun-2016 1:50:13 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Historia generated by hbm2java
 */
@Entity
@Table(name = "historia")
public class Historia implements java.io.Serializable {

	@Id
	@GeneratedValue
	private Integer id;
	private int paciente;
	private String fecha;
	private Float altura;
	private Float peso;
	private String antecedentes;
	private String evolucion;
	private String laboratorio;
	private String otros;
	private String observaciones;
	private String diagprinc;
	private String diagsec;
	private String especialista;

	public Historia() {
	}

	public Historia(int paciente, String fecha, String especialista) {
		this.paciente = paciente;
		this.fecha = fecha;
		this.especialista = especialista;
	}

	public Historia(int paciente, String fecha, Float altura, Float peso, String antecedentes, String evolucion,
			String laboratorio, String otros, String observaciones, String diagprinc, String diagsec,
			String especialista) {
		this.paciente = paciente;
		this.fecha = fecha;
		this.altura = altura;
		this.peso = peso;
		this.antecedentes = antecedentes;
		this.evolucion = evolucion;
		this.laboratorio = laboratorio;
		this.otros = otros;
		this.observaciones = observaciones;
		this.diagprinc = diagprinc;
		this.diagsec = diagsec;
		this.especialista = especialista;
	}
	@GenericGenerator(name = "generator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator")
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", nullable = false)

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getPaciente() {
		return this.paciente;
	}

	public void setPaciente(int paciente) {
		this.paciente = paciente;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public Float getAltura() {
		return this.altura;
	}

	public void setAltura(Float altura) {
		this.altura = altura;
	}

	public Float getPeso() {
		return this.peso;
	}

	public void setPeso(Float peso) {
		this.peso = peso;
	}

	public String getAntecedentes() {
		return this.antecedentes;
	}

	public void setAntecedentes(String antecedentes) {
		this.antecedentes = antecedentes;
	}

	public String getEvolucion() {
		return this.evolucion;
	}

	public void setEvolucion(String evolucion) {
		this.evolucion = evolucion;
	}

	public String getLaboratorio() {
		return this.laboratorio;
	}

	public void setLaboratorio(String laboratorio) {
		this.laboratorio = laboratorio;
	}

	public String getOtros() {
		return this.otros;
	}

	public void setOtros(String otros) {
		this.otros = otros;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getDiagprinc() {
		return this.diagprinc;
	}

	public void setDiagprinc(String diagprinc) {
		this.diagprinc = diagprinc;
	}

	public String getDiagsec() {
		return this.diagsec;
	}

	public void setDiagsec(String diagsec) {
		this.diagsec = diagsec;
	}

	public String getEspecialista() {
		return this.especialista;
	}

	public void setEspecialista(String especialista) {
		this.especialista = especialista;
	}

}
