package com.histocons.entidades;
// Generated 20-jun-2016 1:50:13 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name = "provincia")
public class Provincia implements java.io.Serializable {

	@Id
	@GeneratedValue
	private short id;
	private String provinciaNombre;

	public Provincia() {
	}

	public Provincia(short id, String provinciaNombre) {
		this.id = id;
		this.provinciaNombre = provinciaNombre;
	}
	@GenericGenerator(name = "generator", strategy = "org.hibernate.id.enhanced.SequenceStyleGenerator")
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", nullable = false)

	public short getId() {
		return this.id;
	}

	public void setId(short id) {
		this.id = id;
	}

	public String getProvinciaNombre() {
		return this.provinciaNombre;
	}

	public void setProvinciaNombre(String provinciaNombre) {
		this.provinciaNombre = provinciaNombre;
	}

}
