package com.historiasclinicas.entidades;
// Generated 18-feb-2017 9:47:15 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ciudad generated by hbm2java
 */
@Entity
@Table(name = "ciudad", catalog = "histocons")
public class Ciudad implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -7781406623459851073L;
	private String ciudadnombre;
	private int id;

	public Ciudad() {
	}

	public Ciudad(int id, String ciudadnombre) {
		this.id = id;
		this.ciudadnombre = ciudadnombre;
	}

	@Column(name = "ciudadnombre", nullable = false, length = 60)
	public String getCiudadnombre() {
		return ciudadnombre;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return id;
	}

	public void setCiudadnombre(String ciudadnombre) {
		this.ciudadnombre = ciudadnombre;
	}

	public void setId(int id) {
		this.id = id;
	}

}
