package com.historiasclinicas.entidades;
// Generated 18-feb-2017 9:47:15 by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estados generated by hbm2java
 */
@Entity
@Table(name = "estados", catalog = "histocons")
public class Estados implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -8933647522606250075L;
	private String estado;
	private int id;
	private Set<Turnos> turnoses = new HashSet<>(0);

	public Estados() {
	}

	public Estados(int id, String estado) {
		this.id = id;
		this.estado = estado;
	}

	public Estados(int id, String estado, Set<Turnos> turnoses) {
		this.id = id;
		this.estado = estado;
		this.turnoses = turnoses;
	}

	@Column(name = "estado", nullable = false, length = 45)
	public String getEstado() {
		return estado;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return id;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estados")
	public Set<Turnos> getTurnoses() {
		return turnoses;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public void setId(int id) {
		this.id = id;
	}

	public void setTurnoses(Set<Turnos> turnoses) {
		this.turnoses = turnoses;
	}

}
