package com.historiasclinicas.entidades;
// Generated 18-feb-2017 9:47:15 by Hibernate Tools 5.2.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Historia generated by hbm2java
 */
@Entity
@Table(name = "historia", catalog = "histocons")
public class Historia implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -4531574716575010100L;
	private String antecedentes;
	private String diagprinc;
	private String diagsec;
	private String especialidad;
	private String especialista;
	private String evolucion;
	private Date fecha;
	private Integer id;
	private String laboratorio;
	private String observaciones;
	private Integer orden;
	private String otros;
	private int paciente;

	public Historia() {
	}

	public Historia(int paciente, Date fecha, String especialista) {
		this.paciente = paciente;
		this.fecha = fecha;
		this.especialista = especialista;
	}

	public Historia(int paciente, Date fecha, String antecedentes, String evolucion, String laboratorio, String otros,
			String observaciones, String diagprinc, String diagsec, String especialista, String especialidad,
			Integer orden) {
		this.paciente = paciente;
		this.fecha = fecha;
		this.antecedentes = antecedentes;
		this.evolucion = evolucion;
		this.laboratorio = laboratorio;
		this.otros = otros;
		this.observaciones = observaciones;
		this.diagprinc = diagprinc;
		this.diagsec = diagsec;
		this.especialista = especialista;
		this.especialidad = especialidad;
		this.orden = orden;
	}

	@Column(name = "antecedentes")
	public String getAntecedentes() {
		return antecedentes;
	}

	@Column(name = "diagprinc")
	public String getDiagprinc() {
		return diagprinc;
	}

	@Column(name = "diagsec")
	public String getDiagsec() {
		return diagsec;
	}

	@Column(name = "especialidad", length = 45)
	public String getEspecialidad() {
		return especialidad;
	}

	@Column(name = "especialista", nullable = false, length = 100)
	public String getEspecialista() {
		return especialista;
	}

	@Column(name = "evolucion")
	public String getEvolucion() {
		return evolucion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", nullable = false, length = 19)
	public Date getFecha() {
		return fecha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	@Column(name = "laboratorio")
	public String getLaboratorio() {
		return laboratorio;
	}

	@Column(name = "observaciones")
	public String getObservaciones() {
		return observaciones;
	}

	@Column(name = "orden")
	public Integer getOrden() {
		return orden;
	}

	@Column(name = "otros")
	public String getOtros() {
		return otros;
	}

	@Column(name = "paciente", nullable = false)
	public int getPaciente() {
		return paciente;
	}

	public void setAntecedentes(String antecedentes) {
		this.antecedentes = antecedentes;
	}

	public void setDiagprinc(String diagprinc) {
		this.diagprinc = diagprinc;
	}

	public void setDiagsec(String diagsec) {
		this.diagsec = diagsec;
	}

	public void setEspecialidad(String especialidad) {
		this.especialidad = especialidad;
	}

	public void setEspecialista(String especialista) {
		this.especialista = especialista;
	}

	public void setEvolucion(String evolucion) {
		this.evolucion = evolucion;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setLaboratorio(String laboratorio) {
		this.laboratorio = laboratorio;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	public void setOtros(String otros) {
		this.otros = otros;
	}

	public void setPaciente(int paciente) {
		this.paciente = paciente;
	}

}
