package com.historiasclinicas.entidades;
// Generated 18-feb-2017 9:47:15 by Hibernate Tools 5.2.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Obrassociales generated by hbm2java
 */
@Entity
@Table(name = "obrassociales", catalog = "histocons", uniqueConstraints = @UniqueConstraint(columnNames = "nombreOS"))
public class Obrassociales implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1819301078631400855L;
	private Integer id;
	private String nombreOs;

	public Obrassociales() {
	}

	public Obrassociales(String nombreOs) {
		this.nombreOs = nombreOs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	@Column(name = "nombreOS", unique = true, nullable = false, length = 45)
	public String getNombreOs() {
		return nombreOs;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setNombreOs(String nombreOs) {
		this.nombreOs = nombreOs;
	}

}
