package com.historiasclinicas.entidades;
// Generated 18-feb-2017 9:47:15 by Hibernate Tools 5.2.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Otrasvacunas generated by hbm2java
 */
@Entity
@Table(name = "otrasvacunas", catalog = "histocons")
public class Otrasvacunas implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -643313754860865510L;
	private String fechaVacuna;
	private Integer idOtrasVacunas;
	private String nombreVacuna;
	private int paciente;

	public Otrasvacunas() {
	}

	public Otrasvacunas(int paciente) {
		this.paciente = paciente;
	}

	public Otrasvacunas(int paciente, String nombreVacuna, String fechaVacuna) {
		this.paciente = paciente;
		this.nombreVacuna = nombreVacuna;
		this.fechaVacuna = fechaVacuna;
	}

	@Column(name = "fechaVacuna", length = 100)
	public String getFechaVacuna() {
		return fechaVacuna;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idOtrasVacunas", unique = true, nullable = false)
	public Integer getIdOtrasVacunas() {
		return idOtrasVacunas;
	}

	@Column(name = "nombreVacuna", length = 100)
	public String getNombreVacuna() {
		return nombreVacuna;
	}

	@Column(name = "paciente", nullable = false)
	public int getPaciente() {
		return paciente;
	}

	public void setFechaVacuna(String fechaVacuna) {
		this.fechaVacuna = fechaVacuna;
	}

	public void setIdOtrasVacunas(Integer idOtrasVacunas) {
		this.idOtrasVacunas = idOtrasVacunas;
	}

	public void setNombreVacuna(String nombreVacuna) {
		this.nombreVacuna = nombreVacuna;
	}

	public void setPaciente(int paciente) {
		this.paciente = paciente;
	}

}
