package com.historiasclinicas.entidades;
// Generated 18-feb-2017 9:47:15 by Hibernate Tools 5.2.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Paciente generated by hbm2java
 */
@Entity
@Table(name = "paciente", catalog = "histocons", uniqueConstraints = @UniqueConstraint(columnNames = "dni"))
public class Paciente implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -242348769564376504L;
	private String apellido;
	private Integer ciudad;
	private String correo;
	private Integer dni;
	private String domicilio;
	private Date fechaNacimiento;
	private String gruposanguineo;
	private Integer id;
	private String nombre;
	private String nroAfiliado;
	private Integer obraSocial;
	private String planOs;
	private Integer provincia;
	private int sexo;
	private Long telefono;
	private Long telefonoCelular;

	public Paciente() {
	}

	public Paciente(Integer dni, String nombre, int sexo) {
		this.dni = dni;
		this.nombre = nombre;
		this.sexo = sexo;
	}

	public Paciente(Integer dni, String nombre, String apellido, int sexo, Integer obraSocial, Date fechaNacimiento,
			String planOs, String nroAfiliado, Integer provincia, Integer ciudad, String domicilio, Long telefono,
			Long telefonoCelular, String correo, String gruposanguineo) {
		this.dni = dni;
		this.nombre = nombre;
		this.apellido = apellido;
		this.sexo = sexo;
		this.obraSocial = obraSocial;
		this.fechaNacimiento = fechaNacimiento;
		this.planOs = planOs;
		this.nroAfiliado = nroAfiliado;
		this.provincia = provincia;
		this.ciudad = ciudad;
		this.domicilio = domicilio;
		this.telefono = telefono;
		this.telefonoCelular = telefonoCelular;
		this.correo = correo;
		this.gruposanguineo = gruposanguineo;
	}

	@Column(name = "apellido", length = 100)
	public String getApellido() {
		return apellido;
	}

	@Column(name = "ciudad")
	public Integer getCiudad() {
		return ciudad;
	}

	@Column(name = "correo", length = 150)
	public String getCorreo() {
		return correo;
	}

	@Column(name = "dni", unique = true, nullable = false)
	public Integer getDni() {
		return dni;
	}

	@Column(name = "domicilio", length = 200)
	public String getDomicilio() {
		return domicilio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "fechaNacimiento", length = 10)
	public Date getFechaNacimiento() {
		return fechaNacimiento;
	}

	@Column(name = "gruposanguineo", length = 45)
	public String getGruposanguineo() {
		return gruposanguineo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	@Column(name = "nombre", nullable = false, length = 100)
	public String getNombre() {
		return nombre;
	}

	@Column(name = "nroAfiliado", length = 30)
	public String getNroAfiliado() {
		return nroAfiliado;
	}

	@Column(name = "obraSocial")
	public Integer getObraSocial() {
		return obraSocial;
	}

	@Column(name = "planOs", length = 45)
	public String getPlanOs() {
		return planOs;
	}

	@Column(name = "provincia")
	public Integer getProvincia() {
		return provincia;
	}

	@Column(name = "sexo", nullable = false)
	public int getSexo() {
		return sexo;
	}

	@Column(name = "telefono")
	public Long getTelefono() {
		return telefono;
	}

	@Column(name = "telefonoCelular")
	public Long getTelefonoCelular() {
		return telefonoCelular;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public void setCiudad(Integer ciudad) {
		this.ciudad = ciudad;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public void setDni(int dni) {
		this.dni = dni;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	public void setFechaNacimiento(Date fechaNacimiento) {
		this.fechaNacimiento = fechaNacimiento;
	}

	public void setGruposanguineo(String gruposanguineo) {
		this.gruposanguineo = gruposanguineo;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public void setNroAfiliado(String nroAfiliado) {
		this.nroAfiliado = nroAfiliado;
	}

	public void setObraSocial(Integer obraSocial) {
		this.obraSocial = obraSocial;
	}

	public void setPlanOs(String planOs) {
		this.planOs = planOs;
	}

	public void setProvincia(Integer provincia) {
		this.provincia = provincia;
	}

	public void setSexo(int sexo) {
		this.sexo = sexo;
	}

	public void setTelefono(Long telefono) {
		this.telefono = telefono;
	}

	public void setTelefonoCelular(Long telefonoCelular) {
		this.telefonoCelular = telefonoCelular;
	}

}
