package com.historiasclinicas.entidades;
// Generated 18-feb-2017 9:47:15 by Hibernate Tools 5.2.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Planillapediatrica generated by hbm2java
 */
@Entity
@Table(name = "planillapediatrica", catalog = "histocons")
public class Planillapediatrica implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -541178902185643007L;
	private Integer aborto;
	private Boolean accPer;
	private Boolean alergiaFamiliares;
	private Boolean alergiasPer;
	private Integer apgar1;
	private Integer apgar5;
	private Boolean asmaFamiliares;
	private Boolean asmaPer;
	private Boolean cancerFamiliares;
	private Boolean cardiopatFamiliares;
	private Integer cesarea;
	private Boolean cirugiasPer;
	private Boolean colagenopFamiliares;
	private Boolean dbtFamiliares;
	private Boolean dbtPer;
	private Boolean digestivos;
	private String egest;
	private Boolean epilepsiaFamiliares;
	private Boolean erroresCong;
	private Integer gesta;
	private Boolean hematOncFamiliares;
	private Boolean hematoPer;
	private Boolean htafamiliares;
	private Integer id;
	private Boolean infecUrPer;
	private String medPerm;
	private Boolean migranaFamiliares;
	private Boolean miopiaFamiliares;
	private Boolean neumPer;
	private Boolean neuropsiqFamiliares;
	private Boolean neurPer;
	private Boolean obesidadFamiliares;
	private Boolean otitisPer;
	private String otrosFamiliares;
	private String otrosPersonales;
	private int paciente;
	private Boolean paperasPer;
	private Integer parto;
	private String patolDelRn;
	private Integer perCef;
	private Integer peso;
	private Boolean psicolPer;
	private Boolean rubeolaPer;
	private Boolean sarampPer;
	private Boolean tabaqFamiliares;
	private Integer talal;
	private Boolean varicelaPer;

	public Planillapediatrica() {
	}

	public Planillapediatrica(int paciente) {
		this.paciente = paciente;
	}

	public Planillapediatrica(Integer gesta, Integer parto, Integer cesarea, Integer aborto, Integer peso,
			Integer talal, Integer perCef, Integer apgar1, Integer apgar5, String egest, String patolDelRn,
			Boolean erroresCong, int paciente, Boolean asmaPer, Boolean alergiasPer, Boolean neurPer, Boolean neumPer,
			Boolean paperasPer, Boolean psicolPer, Boolean accPer, Boolean hematoPer, Boolean rubeolaPer,
			Boolean otitisPer, Boolean sarampPer, Boolean varicelaPer, Boolean infecUrPer, Boolean cirugiasPer,
			Boolean dbtPer, Boolean digestivos, Boolean dbtFamiliares, Boolean asmaFamiliares,
			Boolean alergiaFamiliares, Boolean tabaqFamiliares, Boolean htafamiliares, Boolean cardiopatFamiliares,
			Boolean colagenopFamiliares, Boolean epilepsiaFamiliares, Boolean obesidadFamiliares,
			Boolean migranaFamiliares, Boolean cancerFamiliares, Boolean miopiaFamiliares, Boolean neuropsiqFamiliares,
			Boolean hematOncFamiliares, String otrosPersonales, String otrosFamiliares, String medPerm) {
		this.gesta = gesta;
		this.parto = parto;
		this.cesarea = cesarea;
		this.aborto = aborto;
		this.peso = peso;
		this.talal = talal;
		this.perCef = perCef;
		this.apgar1 = apgar1;
		this.apgar5 = apgar5;
		this.egest = egest;
		this.patolDelRn = patolDelRn;
		this.erroresCong = erroresCong;
		this.paciente = paciente;
		this.asmaPer = asmaPer;
		this.alergiasPer = alergiasPer;
		this.neurPer = neurPer;
		this.neumPer = neumPer;
		this.paperasPer = paperasPer;
		this.psicolPer = psicolPer;
		this.accPer = accPer;
		this.hematoPer = hematoPer;
		this.rubeolaPer = rubeolaPer;
		this.otitisPer = otitisPer;
		this.sarampPer = sarampPer;
		this.varicelaPer = varicelaPer;
		this.infecUrPer = infecUrPer;
		this.cirugiasPer = cirugiasPer;
		this.dbtPer = dbtPer;
		this.digestivos = digestivos;
		this.dbtFamiliares = dbtFamiliares;
		this.asmaFamiliares = asmaFamiliares;
		this.alergiaFamiliares = alergiaFamiliares;
		this.tabaqFamiliares = tabaqFamiliares;
		this.htafamiliares = htafamiliares;
		this.cardiopatFamiliares = cardiopatFamiliares;
		this.colagenopFamiliares = colagenopFamiliares;
		this.epilepsiaFamiliares = epilepsiaFamiliares;
		this.obesidadFamiliares = obesidadFamiliares;
		this.migranaFamiliares = migranaFamiliares;
		this.cancerFamiliares = cancerFamiliares;
		this.miopiaFamiliares = miopiaFamiliares;
		this.neuropsiqFamiliares = neuropsiqFamiliares;
		this.hematOncFamiliares = hematOncFamiliares;
		this.otrosPersonales = otrosPersonales;
		this.otrosFamiliares = otrosFamiliares;
		this.medPerm = medPerm;
	}

	@Column(name = "Aborto")
	public Integer getAborto() {
		return aborto;
	}

	@Column(name = "AccPer")
	public Boolean getAccPer() {
		return accPer;
	}

	@Column(name = "AlergiaFamiliares")
	public Boolean getAlergiaFamiliares() {
		return alergiaFamiliares;
	}

	@Column(name = "AlergiasPer")
	public Boolean getAlergiasPer() {
		return alergiasPer;
	}

	@Column(name = "Apgar1")
	public Integer getApgar1() {
		return apgar1;
	}

	@Column(name = "Apgar5")
	public Integer getApgar5() {
		return apgar5;
	}

	@Column(name = "AsmaFamiliares")
	public Boolean getAsmaFamiliares() {
		return asmaFamiliares;
	}

	@Column(name = "AsmaPer")
	public Boolean getAsmaPer() {
		return asmaPer;
	}

	@Column(name = "CancerFamiliares")
	public Boolean getCancerFamiliares() {
		return cancerFamiliares;
	}

	@Column(name = "cardiopatFamiliares")
	public Boolean getCardiopatFamiliares() {
		return cardiopatFamiliares;
	}

	@Column(name = "Cesarea")
	public Integer getCesarea() {
		return cesarea;
	}

	@Column(name = "CirugiasPer")
	public Boolean getCirugiasPer() {
		return cirugiasPer;
	}

	@Column(name = "colagenopFamiliares")
	public Boolean getColagenopFamiliares() {
		return colagenopFamiliares;
	}

	@Column(name = "dbtFamiliares")
	public Boolean getDbtFamiliares() {
		return dbtFamiliares;
	}

	@Column(name = "dbtPer")
	public Boolean getDbtPer() {
		return dbtPer;
	}

	@Column(name = "Digestivos")
	public Boolean getDigestivos() {
		return digestivos;
	}

	@Column(name = "EGest", length = 45)
	public String getEgest() {
		return egest;
	}

	@Column(name = "EpilepsiaFamiliares")
	public Boolean getEpilepsiaFamiliares() {
		return epilepsiaFamiliares;
	}

	@Column(name = "ErroresCong")
	public Boolean getErroresCong() {
		return erroresCong;
	}

	@Column(name = "Gesta")
	public Integer getGesta() {
		return gesta;
	}

	@Column(name = "HematOncFamiliares")
	public Boolean getHematOncFamiliares() {
		return hematOncFamiliares;
	}

	@Column(name = "HematoPer")
	public Boolean getHematoPer() {
		return hematoPer;
	}

	@Column(name = "HTAFamiliares")
	public Boolean getHtafamiliares() {
		return htafamiliares;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	@Column(name = "InfecUrPer")
	public Boolean getInfecUrPer() {
		return infecUrPer;
	}

	@Column(name = "medPerm", length = 65535)
	public String getMedPerm() {
		return medPerm;
	}

	@Column(name = "MigranaFamiliares")
	public Boolean getMigranaFamiliares() {
		return migranaFamiliares;
	}

	@Column(name = "MiopiaFamiliares")
	public Boolean getMiopiaFamiliares() {
		return miopiaFamiliares;
	}

	@Column(name = "NeumPer")
	public Boolean getNeumPer() {
		return neumPer;
	}

	@Column(name = "NeuropsiqFamiliares")
	public Boolean getNeuropsiqFamiliares() {
		return neuropsiqFamiliares;
	}

	@Column(name = "NeurPer")
	public Boolean getNeurPer() {
		return neurPer;
	}

	@Column(name = "ObesidadFamiliares")
	public Boolean getObesidadFamiliares() {
		return obesidadFamiliares;
	}

	@Column(name = "OtitisPer")
	public Boolean getOtitisPer() {
		return otitisPer;
	}

	@Column(name = "OtrosFamiliares", length = 65535)
	public String getOtrosFamiliares() {
		return otrosFamiliares;
	}

	@Column(name = "OtrosPersonales", length = 65535)
	public String getOtrosPersonales() {
		return otrosPersonales;
	}

	@Column(name = "Paciente", nullable = false)
	public int getPaciente() {
		return paciente;
	}

	@Column(name = "PaperasPer")
	public Boolean getPaperasPer() {
		return paperasPer;
	}

	@Column(name = "Parto")
	public Integer getParto() {
		return parto;
	}

	@Column(name = "PatolDelRN", length = 65535)
	public String getPatolDelRn() {
		return patolDelRn;
	}

	@Column(name = "PerCef")
	public Integer getPerCef() {
		return perCef;
	}

	@Column(name = "Peso")
	public Integer getPeso() {
		return peso;
	}

	@Column(name = "PsicolPer")
	public Boolean getPsicolPer() {
		return psicolPer;
	}

	@Column(name = "RubeolaPer")
	public Boolean getRubeolaPer() {
		return rubeolaPer;
	}

	@Column(name = "SarampPer")
	public Boolean getSarampPer() {
		return sarampPer;
	}

	@Column(name = "TabaqFamiliares")
	public Boolean getTabaqFamiliares() {
		return tabaqFamiliares;
	}

	@Column(name = "Talal")
	public Integer getTalal() {
		return talal;
	}

	@Column(name = "VaricelaPer")
	public Boolean getVaricelaPer() {
		return varicelaPer;
	}

	public void setAborto(Integer aborto) {
		this.aborto = aborto;
	}

	public void setAccPer(Boolean accPer) {
		this.accPer = accPer;
	}

	public void setAlergiaFamiliares(Boolean alergiaFamiliares) {
		this.alergiaFamiliares = alergiaFamiliares;
	}

	public void setAlergiasPer(Boolean alergiasPer) {
		this.alergiasPer = alergiasPer;
	}

	public void setApgar1(Integer apgar1) {
		this.apgar1 = apgar1;
	}

	public void setApgar5(Integer apgar5) {
		this.apgar5 = apgar5;
	}

	public void setAsmaFamiliares(Boolean asmaFamiliares) {
		this.asmaFamiliares = asmaFamiliares;
	}

	public void setAsmaPer(Boolean asmaPer) {
		this.asmaPer = asmaPer;
	}

	public void setCancerFamiliares(Boolean cancerFamiliares) {
		this.cancerFamiliares = cancerFamiliares;
	}

	public void setCardiopatFamiliares(Boolean cardiopatFamiliares) {
		this.cardiopatFamiliares = cardiopatFamiliares;
	}

	public void setCesarea(Integer cesarea) {
		this.cesarea = cesarea;
	}

	public void setCirugiasPer(Boolean cirugiasPer) {
		this.cirugiasPer = cirugiasPer;
	}

	public void setColagenopFamiliares(Boolean colagenopFamiliares) {
		this.colagenopFamiliares = colagenopFamiliares;
	}

	public void setDbtFamiliares(Boolean dbtFamiliares) {
		this.dbtFamiliares = dbtFamiliares;
	}

	public void setDbtPer(Boolean dbtPer) {
		this.dbtPer = dbtPer;
	}

	public void setDigestivos(Boolean digestivos) {
		this.digestivos = digestivos;
	}

	public void setEgest(String egest) {
		this.egest = egest;
	}

	public void setEpilepsiaFamiliares(Boolean epilepsiaFamiliares) {
		this.epilepsiaFamiliares = epilepsiaFamiliares;
	}

	public void setErroresCong(Boolean erroresCong) {
		this.erroresCong = erroresCong;
	}

	public void setGesta(Integer gesta) {
		this.gesta = gesta;
	}

	public void setHematOncFamiliares(Boolean hematOncFamiliares) {
		this.hematOncFamiliares = hematOncFamiliares;
	}

	public void setHematoPer(Boolean hematoPer) {
		this.hematoPer = hematoPer;
	}

	public void setHtafamiliares(Boolean htafamiliares) {
		this.htafamiliares = htafamiliares;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setInfecUrPer(Boolean infecUrPer) {
		this.infecUrPer = infecUrPer;
	}

	public void setMedPerm(String medPerm) {
		this.medPerm = medPerm;
	}

	public void setMigranaFamiliares(Boolean migranaFamiliares) {
		this.migranaFamiliares = migranaFamiliares;
	}

	public void setMiopiaFamiliares(Boolean miopiaFamiliares) {
		this.miopiaFamiliares = miopiaFamiliares;
	}

	public void setNeumPer(Boolean neumPer) {
		this.neumPer = neumPer;
	}

	public void setNeuropsiqFamiliares(Boolean neuropsiqFamiliares) {
		this.neuropsiqFamiliares = neuropsiqFamiliares;
	}

	public void setNeurPer(Boolean neurPer) {
		this.neurPer = neurPer;
	}

	public void setObesidadFamiliares(Boolean obesidadFamiliares) {
		this.obesidadFamiliares = obesidadFamiliares;
	}

	public void setOtitisPer(Boolean otitisPer) {
		this.otitisPer = otitisPer;
	}

	public void setOtrosFamiliares(String otrosFamiliares) {
		this.otrosFamiliares = otrosFamiliares;
	}

	public void setOtrosPersonales(String otrosPersonales) {
		this.otrosPersonales = otrosPersonales;
	}

	public void setPaciente(int paciente) {
		this.paciente = paciente;
	}

	public void setPaperasPer(Boolean paperasPer) {
		this.paperasPer = paperasPer;
	}

	public void setParto(Integer parto) {
		this.parto = parto;
	}

	public void setPatolDelRn(String patolDelRn) {
		this.patolDelRn = patolDelRn;
	}

	public void setPerCef(Integer perCef) {
		this.perCef = perCef;
	}

	public void setPeso(Integer peso) {
		this.peso = peso;
	}

	public void setPsicolPer(Boolean psicolPer) {
		this.psicolPer = psicolPer;
	}

	public void setRubeolaPer(Boolean rubeolaPer) {
		this.rubeolaPer = rubeolaPer;
	}

	public void setSarampPer(Boolean sarampPer) {
		this.sarampPer = sarampPer;
	}

	public void setTabaqFamiliares(Boolean tabaqFamiliares) {
		this.tabaqFamiliares = tabaqFamiliares;
	}

	public void setTalal(Integer talal) {
		this.talal = talal;
	}

	public void setVaricelaPer(Boolean varicelaPer) {
		this.varicelaPer = varicelaPer;
	}

}
