package com.historiasclinicas.entidades;
// Generated 18-feb-2017 9:47:15 by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Provincia generated by hbm2java
 */
@Entity
@Table(name = "provincia", catalog = "histocons")
public class Provincia implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 3412832251339448998L;
	private short id;
	private String provincianombre;

	public Provincia() {
	}

	public Provincia(short id, String provincianombre) {
		this.id = id;
		this.provincianombre = provincianombre;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public short getId() {
		return id;
	}

	@Column(name = "provincianombre", nullable = false, length = 50)
	public String getProvincianombre() {
		return provincianombre;
	}

	public void setId(short id) {
		this.id = id;
	}

	public void setProvincianombre(String provincianombre) {
		this.provincianombre = provincianombre;
	}

}
