package com.historiasclinicas.entidades;
// Generated 18-feb-2017 9:47:15 by Hibernate Tools 5.2.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Turnos generated by hbm2java
 */
@Entity
@Table(name = "turnos", catalog = "histocons")
public class Turnos implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 2766018908124280843L;
	private String especialista;
	private Estados estados;
	private Date fechaTurno;
	private String horaTurno;
	private Integer id;
	private int paciente;
	private String pacienteApellido;
	private String pacienteNombre;

	public Turnos() {
	}

	public Turnos(Estados estados, Date fechaTurno, int paciente, String especialista, String horaTurno,
			String pacienteApellido, String pacienteNombre) {
		this.estados = estados;
		this.fechaTurno = fechaTurno;
		this.paciente = paciente;
		this.especialista = especialista;
		this.horaTurno = horaTurno;
		this.pacienteApellido = pacienteApellido;
		this.pacienteNombre = pacienteNombre;
	}

	@Column(name = "especialista", nullable = false, length = 45)
	public String getEspecialista() {
		return especialista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "estado", nullable = false)
	public Estados getEstados() {
		return estados;
	}

	@Column(name = "fechaTurno", nullable = true, length = 19)
	public Date getFechaTurno() {
		return fechaTurno;
	}

	@Column(name = "horaTurno", nullable = false, length = 45)
	public String getHoraTurno() {
		return horaTurno;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	@Column(name = "paciente", nullable = false)
	public int getPaciente() {
		return paciente;
	}

	@Column(name = "pacienteApellido", nullable = false, length = 45)
	public String getPacienteApellido() {
		return pacienteApellido;
	}

	@Column(name = "pacienteNombre", nullable = false, length = 45)
	public String getPacienteNombre() {
		return pacienteNombre;
	}

	public void setEspecialista(String especialista) {
		this.especialista = especialista;
	}

	public void setEstados(Estados estados) {
		this.estados = estados;
	}

	public void setFechaTurno(Date fechaTurno) {
		this.fechaTurno = fechaTurno;
	}

	public void setHoraTurno(String horaTurno) {
		this.horaTurno = horaTurno;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setPaciente(int paciente) {
		this.paciente = paciente;
	}

	public void setPacienteApellido(String pacienteApellido) {
		this.pacienteApellido = pacienteApellido;
	}

	public void setPacienteNombre(String pacienteNombre) {
		this.pacienteNombre = pacienteNombre;
	}

}
