package com.historiasclinicas.entidades;
// Generated 18-feb-2017 9:47:15 by Hibernate Tools 5.2.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "histocons")
public class Usuarios implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 959708917549922479L;
	private String apellido;
	private String especialidad;
	private Integer id;
	private String isactive;
	private Integer matricula;
	private String nombre;
	private String password;
	private String perfil;
	private String username;

	public Usuarios() {
	}

	public Usuarios(String username, String password, String isactive, String perfil, String nombre, String apellido) {
		this.username = username;
		this.password = password;
		this.isactive = isactive;
		this.perfil = perfil;
		this.nombre = nombre;
		this.apellido = apellido;
	}

	public Usuarios(String username, String password, String isactive, String perfil, String nombre, String apellido,
			String especialidad, Integer matricula) {
		this.username = username;
		this.password = password;
		this.isactive = isactive;
		this.perfil = perfil;
		this.nombre = nombre;
		this.apellido = apellido;
		this.especialidad = especialidad;
		this.matricula = matricula;
	}

	@Column(name = "apellido", nullable = false, length = 45)
	public String getApellido() {
		return apellido;
	}

	@Column(name = "especialidad", length = 45)
	public String getEspecialidad() {
		return especialidad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	@Column(name = "isactive", nullable = false, length = 2)
	public String getIsactive() {
		return isactive;
	}

	@Column(name = "matricula")
	public Integer getMatricula() {
		return matricula;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return nombre;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return password;
	}

	@Column(name = "perfil", nullable = false, length = 12)
	public String getPerfil() {
		return perfil;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return username;
	}

	public void setApellido(String apellido) {
		this.apellido = apellido;
	}

	public void setEspecialidad(String especialidad) {
		this.especialidad = especialidad;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setIsactive(String isactive) {
		this.isactive = isactive;
	}

	public void setMatricula(Integer matricula) {
		this.matricula = matricula;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public void setPerfil(String perfil) {
		this.perfil = perfil;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
